# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - left_arm
    - right_arm

  left_arm:
    type: FollowJointTrajectory
    joints:
      []
    action_ns: follow_joint_trajectory
    default: true
  right_arm:
    type: FollowJointTrajectory
    joints:
      []
    action_ns: follow_joint_trajectory
    default: true