# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    left_arm:
      type: joint_trajectory_controller/JointTrajectoryController


    right_arm:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

left_arm:
  ros__parameters:
    joints:
      []
    command_interfaces:
      []
    state_interfaces:
      []
right_arm:
  ros__parameters:
    joints:
      []
    command_interfaces:
      []
    state_interfaces:
      []